# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAggregator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsAggregator
  pod 'SnapKit'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'

  target 'NewsAggregatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsAggregatorUITests' do
    # Pods for testing
  end

end
